// angular/part-1/conference-app/src/header/header.component.ts
import { Component, Input } from '@angular/core';
import { AchievementSummary, User } from '../api/models';
import { ProfileComponent } from './profile/profile.component';
import { ProgressGraphComponent } from './progress-graph/progress-graph.component';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: "./header.component.scss",
  standalone: true,
  imports: [ProfileComponent, ProgressGraphComponent]
})
export class HeaderComponent {
  @Input() user!: User;
  @Input() achievementSummary!: AchievementSummary;
}

// react/part-1/conference-app/src/Header/Header.tsx
import { AchievementSummary, User } from '../api/models';
import { Profile } from './Profile/Profile';
import { ProgressGraph } from './ProgressGraph/ProgressGraph';
import styles from './Header.module.scss';

export interface HeaderProps {
  user: User;
  achievementSummary: AchievementSummary;
}

export function Header(props: HeaderProps) {
  return (
    <div className={styles.headerContainer}>
      <div className={styles.headerLeft}>
        <Profile user={props.user} />
      </div>
      <div>
        <ProgressGraph achievementSummary={props.achievementSummary} />
      </div>
    </div>
  );
}
