// react/solution/conference-app/examples/AchievementGrid/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.scss';
import { AchievementData } from '@conference-app/Shared-Models';
import { AchievementGrid } from '@conference-app/AchievementGrid';
import { Server } from 'miragejs';

new Server({
  routes() {
    this.post('http://localhost:5001/api/appdata/achievements/:achievementId/increment', (schema, request) => {
      const id = request.params.achievementId;
      console.log(`Incrementing achievement ${id}...`);
      return {}
    })
  }
})

export function App() {
  const mockAchievements: AchievementData[] = [
    {id: 1, title: "Example", progress: 0, goal: 5, status: "uncompleted", styleType: 1}
  ];

  return (
    <div>
      <AchievementGrid achievements={mockAchievements} reloadData={() => console.log("Reload called")}/>
    </div>
  );
}

export default App;

// angular/solution/conference-app/examples/achievement-grid/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { AchievementGridComponent } from "@conference-app/achievement-grid";
import { Server } from 'miragejs';
import { AchievementData } from "@conference-app/shared-models";

@Component({
  standalone: true,
  imports: [AchievementGridComponent],
  selector: 'conference-app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  title = 'example-achievement-grid';

  public mockAchievements: AchievementData[] = [
    {id: 1, title: "Example", progress: 0, goal: 5, status: "uncompleted", styleType: 1}
  ];

  ngOnInit() {
    new Server({
      routes() {
        this.post('http://localhost:5001/api/appdata/achievements/:achievementId/increment', (_schema, request: any) => {
          const id = request.params.achievementId;
          console.log(`Incrementing achievement ${id}...`);
          return {}
        })
      }
    })
  }

  handleReloadData() {
    console.log("Reload called");
  }
}
