// angular/solution/conference-app/libs/header/src/lib/header/progress-graph/progress-graph.component.ts
import { Component, Input, OnChanges, OnInit } from '@angular/core';
import { AchievementSummary } from '@conference-app/shared-models';
import Chart from "chart.js/auto";

@Component({
  selector: 'app-progress-graph',
  templateUrl: './progress-graph.component.html',
  styleUrl: './progress-graph.component.scss',
  standalone: true
})
export class ProgressGraphComponent implements OnInit, OnChanges {
  @Input() achievementSummary!: AchievementSummary;

  public chart: any;

  ngOnInit() {
    this.initializeChart();
  }

  ngOnChanges() {
    if (this.chart) {
      this.chart.data.datasets[0].data = [this.completed, this.uncompleted];
      this.chart.update();
    }
  }

  private initializeChart() {
    this.chart = new Chart("canvas", {
      type: "doughnut",
      data: {
        datasets: [
          {
            label: '',
            data: [this.completed, this.uncompleted],
            backgroundColor: [
              'rgba(255, 226, 0, 1)',
              'rgba(0, 0, 0, 0.4)'
            ],
            borderWidth: 0,
    
          },
        ]
      },
      options: {
        responsive: true,
        plugins: {
          tooltip: {
            enabled: true
          }
        }
      }
    });
  }

  get total(): number {
    return this.achievementSummary?.total;
  }

  get completed(): number {
    return this.achievementSummary?.completed;
  }

  get uncompleted(): number {
    return this.achievementSummary?.uncompleted;
  }
}

// react/solution/conference-app/libs/Header/src/lib/ProgressGraph/ProgressGraph.tsx
import { Chart as ChartJS, ArcElement, ChartData, ChartOptions, Tooltip } from "chart.js";
import { Doughnut } from "react-chartjs-2";
import { AchievementSummary } from '@conference-app/Shared-Models';
import styles from './ProgressGraph.module.scss';

export interface ProgressGraphProps {
    achievementSummary: AchievementSummary;
}

ChartJS.register(ArcElement, Tooltip);

export function ProgressGraph(props: ProgressGraphProps) {
    const total = props.achievementSummary.total;
    const completed = props.achievementSummary.completed;
    const uncompleted = props.achievementSummary.uncompleted;

    const options: ChartOptions<"doughnut"> = {
        responsive: true,
        plugins: {
            tooltip: {
                enabled: true,
            },
        }
    }
    const data: ChartData<"doughnut", number[], string> = {
        labels: ['Completed', 'Uncompleted'],
        datasets: [
            {
                label: '',
                data: [completed, uncompleted],
                backgroundColor: [
                    'rgba(255, 226, 0, 1)',
                    'rgba(0, 0, 0, 0.4)'
                ],
                borderWidth: 0,

            },
        ],
    };

    return (
        <div className={styles.progressGraphContainer}>
            <Doughnut data={data} options={options} />
            <div className={styles.doughnutText}>{`${completed}/${total}`}</div>
        </div>
    )
}
