// react/part-3/conference-app/libs/Header/src/lib/Header.tsx
import { AchievementSummary, User } from '@conference-app/Shared-Models';
import { Profile } from './Profile/Profile';
import { ProgressGraph } from './ProgressGraph/ProgressGraph';
import styles from './Header.module.scss';

export interface HeaderProps {
  user: User;
  achievementSummary: AchievementSummary;
}

export function Header(props: HeaderProps) {
  return (
    <div className={styles.headerContainer}>
      <div className={styles.headerLeft}>
        <Profile user={props.user} />
      </div>
      <div>
        <ProgressGraph achievementSummary={props.achievementSummary} />
      </div>
    </div>
  );
}

// angular/solution/conference-app/libs/header/src/lib/header/header.component.ts
import { Component, Input } from '@angular/core';
import { AchievementSummary, User } from '@conference-app/shared-models';
import { ProfileComponent } from './profile/profile.component';
import { ProgressGraphComponent } from './progress-graph/progress-graph.component';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: "./header.component.scss",
  standalone: true,
  imports: [ProfileComponent, ProgressGraphComponent]
})
export class HeaderComponent {
  @Input() user!: User;
  @Input() achievementSummary!: AchievementSummary;
}
<div class="headerContainer">
  <div class="headerLeft">
    <app-profile [user]="user"></app-profile>
  </div>
  <div>
    <app-progress-graph [achievementSummary]="achievementSummary"></app-progress-graph>
  </div>
</div>
