// angular/part-1/conference-app/src/achievement-grid/achievement/achievement.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { StyledContainerComponent } from '../../components/styled-container/styled-container.component';
import { AchievementData } from '../../api/models';
import { CommonModule } from '@angular/common';
import { AchievementGridService } from '../../api/achievement-grid.service';

@Component({
  selector: 'app-achievement',
  standalone: true,
  imports: [StyledContainerComponent, CommonModule],
  templateUrl: './achievement.component.html',
  styleUrl: './achievement.component.scss'
})
export class AchievementComponent {
  @Input() achievement!: AchievementData;
  @Output() reloadData: EventEmitter<void> = new EventEmitter<void>();

  constructor(private achievementGridService: AchievementGridService) {}

  async increment() {
    await this.achievementGridService.submitIncrementAchievement(this.achievement.id);
    this.reloadData.emit();
  }
}

<app-styled-container [borderRadius]="12" [styleType]="achievement.styleType">
    <div class="achievement">

        <div class='achievementTitle'>{{ achievement.title }}</div>

        <span *ngIf="achievement.progress === achievement.goal">Completed ⭐</span>

        <span *ngIf="achievement.progress < achievement.goal">
            <progress [value]="achievement.progress" [max]="achievement.goal"></progress>
            <span class="achievementProgressText">{{ achievement.progress }}/{{ achievement.goal }}</span>
        </span>

        <button *ngIf="achievement.status !== 'completed'" class="achievementButton" (click)="increment()">+1</button>

    </div>
</app-styled-container>

// react/part-3/conference-app/libs/AchievementGrid/src/lib/Achievement/Achievement.tsx
import { StyledContainer } from '@conference-app/Shared-UI';
import { AchievementData } from '@conference-app/Shared-Models';
import { submitIncrementAchievement } from '../../api/submitIncrementAchievement';
import styles from './Achievement.module.scss';

export interface AchievementProps {
    achievement: AchievementData,
    reloadData: () => void;
}

export function Achievement({ achievement, reloadData }: AchievementProps) {
    const increment = async () => {
        await submitIncrementAchievement(achievement.id);
        reloadData();
    }
    return (
        <StyledContainer styleType={achievement.styleType} borderRadius={12}>
            <div className={styles.achievement}>
                <div className={styles.achievementTitle}>{achievement.title}</div>
                {RenderProgress(achievement.progress, achievement.goal)}
                {achievement.status !== "completed" &&
                    // Style this better
                    <button className={styles.achievementButton} onClick={increment}>+1</button>
                }
            </div>
        </StyledContainer>
    )
}

function RenderProgress(progress: number, max: number) {
    if (progress === max) {
        return <span>Completed ⭐</span>;
    } else {
        return (
            <span>
                <progress value={progress} max={max} />
                <span className={styles.achievementProgressText}>{progress}/{max}</span>
            </span>)
    }
}
