// react/part-1/conference-app/src/AchievementGrid/AchievementGrid.tsx
import React, { useEffect } from 'react';
import {Achievement} from './Achievement/Achievement';
import {Modal} from '../Components/Modal';
import {AchievementForm} from '../AchievementForm/AchievementForm';
import { AchievementData } from '../api/models';
import styles from './AchievementGrid.module.scss';

export interface AchievementGridProps {
    achievements: AchievementData[];
    reloadData: () => void;
}

export function AchievementGrid(props: AchievementGridProps) {
    const [isOpen, setIsOpen] = React.useState(false);
    const [filter, setFilter] = React.useState('All');
    const [filteredAchievements, setFilteredAchievements] = React.useState(props.achievements);

    const LoadGrid = React.useCallback(() => {
        if (filter === 'All') {
            setFilteredAchievements(props.achievements);
        } else if (filter === 'Completed') {
            setFilteredAchievements(props.achievements.filter((achievement) => achievement.status === "completed"));
        } else if (filter === 'Uncompleted') {
            setFilteredAchievements(props.achievements.filter((achievement) => achievement.status === "uncompleted"));
        }
    }, [props.achievements, filter]);
    
    useEffect(() => {
        LoadGrid();
    }, [LoadGrid]);

    const openAddAchiementForm = () => {
        setIsOpen(true);
    }

    const closeAddAchiementForm = () => {
        setIsOpen(false);
        props.reloadData();
    }

    const filterChanged = (e: React.ChangeEvent<HTMLSelectElement>) => {
        setFilter(e.target.value);
    }

    return (
        <>
            <div className={styles.achievementGridContainer}>
                <div className={styles.achievementGridControls}>
                    <button onClick={openAddAchiementForm}>Add</button>
                    <select defaultValue={"All"} onChange={filterChanged} value={filter}>
                        <option value='All'>All</option>
                        <option value='Completed' >Completed</option>
                        <option value='Uncompleted' >Uncompleted</option>
                    </select>
                </div>
                <div className={styles.achievementGridFivider}></div>
                <div className={styles.achievementGrid}>
                    {filteredAchievements.map(achievement => (
                        <Achievement key={achievement.id} achievement={achievement} reloadData={props.reloadData}/>
                    ))}
                </div>
            </div>

            <Modal isOpen={isOpen}>
                <AchievementForm onClose={closeAddAchiementForm}/>
            </Modal>
        </>
    )
}

// angular/part-1/conference-app/src/achievement-grid/achievement-grid.component.ts
import { Component, EventEmitter, Input, OnChanges, OnInit, Output } from '@angular/core';
import { ModalComponent } from '../components/modal/modal.component';
import { AchievementFormComponent } from '../achievement-form/achievement-form.component';
import { AchievementComponent } from './achievement/achievement.component';
import { AchievementData } from '../api/models';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-achievement-grid',
  templateUrl: './achievement-grid.component.html',
  styleUrl: './achievement-grid.component.scss',
  standalone: true,
  imports: [ModalComponent, AchievementFormComponent, AchievementComponent, CommonModule]
})
export class AchievementGridComponent implements OnInit, OnChanges {
  @Input() achievements: AchievementData[] = [];
  @Output() reloadData: EventEmitter<void> = new EventEmitter<void>();

  isOpen = false;
  filter = 'All';
  filteredAchievements: AchievementData[] = [];

  ngOnInit() {
    this.loadGrid();
  }

  ngOnChanges() {
    this.loadGrid();
  }

  loadGrid() {
    if (this.filter === 'All') {
      this.filteredAchievements = this.achievements;
    } else if (this.filter === 'Completed') {
      this.filteredAchievements = this.achievements.filter(achievement => achievement.status === 'completed');
    } else if (this.filter === 'Uncompleted') {
      this.filteredAchievements = this.achievements.filter(achievement => achievement.status === 'uncompleted');
    }
  }

  openAddAchievementForm() {
    this.isOpen = true;
  }

  closeAddAchievementForm() {
    this.isOpen = false;
    this.reloadData.emit();
  }

  filterChanged(event: Event): void {
    const target = event.target as HTMLSelectElement;
    this.filter = target.value;
    this.loadGrid();
  }
}
