// angular/solution/conference-app/examples/achievement-form/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { AchievementFormComponent } from "@conference-app/achievement-form";
import { SubmitAchievement } from "@conference-app/shared-models";
import { Server } from 'miragejs';

@Component({
  standalone: true,
  imports: [AchievementFormComponent],
  selector: 'conference-app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent implements OnInit {
  title = 'example-achievement-form';

  ngOnInit() {
    new Server({
      routes() {
        this.post('http://localhost:5001/api/appdata/achievements', (_schema, request) => {
          const achievement: SubmitAchievement = JSON.parse(request.requestBody);
          console.log(achievement);
          return {}
        })
      }
    })
  }

  handleOnClose() {
    console.log("onCloseCalled");
  }
}

<app-achievement-form (onClose)="handleOnClose()"></app-achievement-form>

// react/solution/conference-app/examples/AchievementForm/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.scss';
import { AchievementForm } from '@conference-app/AchievementForm';
import { SubmitAchievement } from '@conference-app/Shared-Models';
import { Server } from 'miragejs';

new Server({
  routes() {
    this.post('http://localhost:5001/api/appdata/achievements', (schema, request) => {
      const achievement: SubmitAchievement = JSON.parse(request.requestBody);
      console.log(achievement);
      return {}
    })
  }
})

export function App() {
  return (
    <div>
      <AchievementForm onClose={() => console.log("onClose called")} />
    </div>
  );
}

export default App;
