// react/solution/conference-app/examples/Header/src/app/app.tsx
import styles from './app.module.scss';
import { Header } from '@conference-app/Header';

export function App() {
  const userInfo = {id: 10, name: "John Doe", profileImage: "https://picsum.photos/150/150"};
  var summaryInfo = {completed: 1000000, uncompleted: 3, total: 100000}

  return (
    <div>
      <Header achievementSummary={summaryInfo} user={userInfo}/>
    </div>
  );
}

export default App;

// angular/solution/conference-app/examples/header/src/app/app.component.ts
import { Component } from '@angular/core';
import { User, AchievementSummary } from "@conference-app/shared-models";
import { HeaderComponent } from "@conference-app/header";

@Component({
  standalone: true,
  imports: [HeaderComponent],
  selector: 'conference-app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  title = 'example-header';

  public userInfo: User = {id: 10, name: "John Doe", profileImage: "https://picsum.photos/150/150"};
  public summaryInfo: AchievementSummary = {completed: 2, uncompleted: 3, total: 5};
}

<div>
    <app-header [achievementSummary]="summaryInfo" [user]="userInfo"></app-header>
</div>
